CREATE TABLE CATEGORIAS (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORIAS(nome) VALUE ('Lazer');
INSERT INTO CATEGORIAS(nome) VALUE ('Alimentação');
INSERT INTO CATEGORIAS(nome) VALUE ('Saúde');
INSERT INTO CATEGORIAS(nome) VALUE ('Outros');