CREATE TABLE telefones(
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    numero VARCHAR(15) NOT NULL ,
    id_fornecedor BIGINT(20) ,
    CONSTRAINT FK_TELEFONE_FORNECEDOR_ID FOREIGN KEY (id_fornecedor) REFERENCES fornecedores(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;