CREATE TABLE clientes (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
  	data_nascimento DATE NOT NULL,
  	nome VARCHAR(255) NOT NULL,
  	id_usuario BIGINT(20) DEFAULT NULL,
  	PRIMARY KEY (id),
  	KEY FK_CLIENTE_USUARIO_ID (id_usuario),
  	CONSTRAINT FK_CLIENTE_USUARIO_ID FOREIGN KEY (id_usuario) REFERENCES usuarios (id)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;