CREATE TABLE atividades (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	momento timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acao VARCHAR(80) NOT NULL,
    titulo VARCHAR(80) NOT NULL,
    id_usuario BIGINT(20) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY FK_ATIVIDADE_USUARIO_ID (id_usuario),
    CONSTRAINT FK_ATIVIDADE_USUARIO_ID FOREIGN KEY (id_usuario) REFERENCES usuarios (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;